name: heyy_buddy
description: "Hey Buddy is a workout tracking and streak-maintaining app that motivates users with hype gym vibes and daily challenges."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2   # 👈 ADDED THIS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0   # <-- Added this

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/abs.png
    - assets/arms.png
    - assets/back.png
    - assets/chest.png
    - assets/legs.png
    - assets/shoulders.png
    - assets/app_logo.png
